version: '3.8'

services:
  parser:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://host.docker.internal:27017  # Для локальной MongoDB
      - BROWSER_HEADLESS=true
    extra_hosts:
      - "host.docker.internal:host-gateway"